export const products = [
  {
    id: 'p1',
    name: 'Bouclé Accent Chair',
    description: 'A cozy, textural bouclé fabric chair with a sculptural rounded back. Perfect for reading nooks or living spaces.',
    price: 499.00,
    category: 'Furniture',
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: 124,
    inStock: true,
  },
  {
    id: 'p2',
    name: 'Minimalist Oak Console',
    description: 'Crafted from solid white oak, this console table features clean lines and a soft, organic finish.',
    price: 850.00,
    category: 'Furniture',
    image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    reviews: 89,
    inStock: true,
  },
  {
    id: 'p3',
    name: 'Textured Ceramic Vase',
    description: 'Hand-thrown ceramic vase with a matte reactive glaze. Every piece is unique.',
    price: 65.00,
    category: 'Decor',
    image: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    reviews: 42,
    inStock: true,
  },
  {
    id: 'p4',
    name: 'Abstract Canvas Art',
    description: 'Original abstract painting featuring earthy tones and bold brush strokes. Framed in natural wood.',
    price: 320.00,
    category: 'Art',
    image: 'https://images.unsplash.com/photo-1544445385-d602324dc865?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: 56,
    inStock: true,
  },
  {
    id: 'p5',
    name: 'Linen Throw Pillow',
    description: '100% European flax linen pillow cover with a soft feather insert. Highly breathable and durable.',
    price: 45.00,
    category: 'Textiles',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    reviews: 210,
    inStock: false,
  },
  {
    id: 'p6',
    name: 'Brass Pendant Light',
    description: 'Mid-century inspired brushed brass pendant light. Provides a warm, ambient glow to any dining area.',
    price: 180.00,
    category: 'Lighting',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    reviews: 78,
    inStock: true,
  },
  {
    id: 'p7',
    name: 'Jute Area Rug',
    description: 'Hand-woven natural jute rug. Adds a layer of organic texture and warmth to wooden floors.',
    price: 220.00,
    category: 'Textiles',
    image: 'https://images.unsplash.com/photo-1585420311756-78832a8ba71e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    reviews: 135,
    inStock: true,
  },
  {
    id: 'p8',
    name: 'Marble Coffee Table',
    description: 'Sleek geometric coffee table featuring a solid Carrera marble top and blackened steel base.',
    price: 1200.00,
    category: 'Furniture',
    image: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    reviews: 28,
    inStock: true,
  }
];

export const categories = ['All', 'Furniture', 'Decor', 'Art', 'Textiles', 'Lighting'];
